import type { Metadata } from "next";
import { Geist, Geist_Mono, Sarabun } from "next/font/google";
import "./globals.css";
import TopBar from "@/components/TopBar";


const sarabun = Sarabun({
  subsets: ["latin", "thai"],
  weight: ["400", "700"],
  variable: "--font-sarabun",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${sarabun.variable} font-sans antialiased`}>
        
        <div className="flex flex-col h-screen">

          <TopBar />

          <main className="flex-1 overflowx-scroll">
            {children}
          </main>

        </div>

      </body>
    </html>
  );
}